name: Issue/Idea
title: '[Issue/Idea] '
description: Report an issue/idea
labels: ['type: issue/idea']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠ Checklist
      description: Before creating you should make sure that you have completed the following steps
      options:
        - label: I checked in [Issues](https://github.com/ShrikerChestTrees/OptiCool/issues)
        - label: I downloaded Java 21 or newer for 64 bit systems
        - label: I downloaded the latest version (pre versions count too)

  - type: textarea
    id: description
    attributes:
      label: Describe your issue/idea
      description: Description of the issue/idea you have found/suggesting
      placeholder: My problem/idea is this (Можно и на русском)
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version OptiCool
      description: The version you found the problem on. (If that is the idea just skip it)
      placeholder: OptiCool
    validations:
      required: true

  - type: textarea
    id: gpuandcpu
    attributes:
      label: What GPU and CPU are you using? (If that is the idea just skip it)
    validations:
      required: true

  - type: textarea
    id: othermods
    attributes:
      label: Other Mods?
      description: Are there other mods that were not originally in the modpack?

  - type: textarea
    id: additions
    attributes:
      label: Additional
      description: Is there anything else that is not on any of these lists?
